name: build-pr
on:
  pull_request_target:
    types:
    - labeled
    - synchronize
env:
  PR_NUMBER: ${{ github.event.number }}

jobs:
  build:
    if: contains( github.event.pull_request.labels.*.name, 'Approved For Test')
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Run Makefile
        run: make release-container VERSION=pr-${PR_NUMBER} QUAY_USER=${QUAY_USER} QUAY_PASSWORD=${QUAY_PASSWORD} LABEL="--label quay.expires-after=7d"
        env: # Or as an environment variable
          QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
          QUAY_USER: ${{ secrets.QUAY_USER }}
