name: build-tag

on:
  push:
    tags:
    - '*'


jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Run Makefile
        run: make release-container VERSION=${GITHUB_REF_NAME} QUAY_USER=${QUAY_USER} QUAY_PASSWORD=${QUAY_PASSWORD}
        env: # Or as an environment variable
          QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
          QUAY_USER: ${{ secrets.QUAY_USER }}
